import type { IconType } from 'react-icons'
import { FaAws, FaJava, FaSlack } from 'react-icons/fa6'
import {
  SiDocker,
  SiGin,
  SiGithubactions,
  SiGnubash,
  SiGo,
  SiGraphql,
  SiLaravel,
  SiLinux,
  SiMongodb,
  SiN8N,
  SiNextdotjs,
  SiOpenapiinitiative,
  SiPhp,
  SiPostgresql,
  SiQdrant,
  SiReact,
  SiReactquery,
  SiReacttable,
  SiRedis,
  SiStyledcomponents,
  SiTailwindcss,
  SiTanstack,
  SiTypescript,
  SiVite,
} from 'react-icons/si'

// Skills without a recognizable brand mark (RAG, eino, …) are simply absent
// and render as text-only chips.
export const skillIcons: Record<string, IconType> = {
  Go: SiGo,
  Java: FaJava,
  PHP: SiPhp,
  'REST APIs': SiOpenapiinitiative,
  GraphQL: SiGraphql,
  TypeScript: SiTypescript,
  React: SiReact,
  'TanStack Query': SiReactquery,
  'TanStack Table': SiReacttable,
  'TanStack Start': SiTanstack,
  'Next.js': SiNextdotjs,
  Laravel: SiLaravel,
  Gin: SiGin,
  'Tailwind CSS': SiTailwindcss,
  'styled-components': SiStyledcomponents,
  Vite: SiVite,
  Docker: SiDocker,
  'Docker Compose': SiDocker,
  Linux: SiLinux,
  'CI/CD': SiGithubactions,
  PostgreSQL: SiPostgresql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  'AWS S3': FaAws,
  Qdrant: SiQdrant,
  n8n: SiN8N,
  Scripting: SiGnubash,
  'Slack API': FaSlack,
}
